tasks:
  - name: Crear folder para datos y asigna permisos
    init: >
      make clean_folder && 
      make Create_Data_Folder
  - name: Iniciar db
    init: >
      make start_db_container
  - name: Iniciar pulsar
    init: >
      make start_pulsar_containers

