tasks:
  - name: Iniciar Pulsar
    init: >
      make clean_folder && 
      make Create_Data_Folder && 
      make start_pulsar_containers
  - name: Iniciar Todos los Microservicios
    init: >
      echo "Presiona ENTER para iniciar los microservicios..." && 
      read -r _ && 
      make start_all
 

