version: "3.8"
networks:
  pulsar:
    driver: bridge
  db_network:
    driver: bridge
  db_2_network:
    driver: bridge
  db_mapear_network:
    driver: bridge

services:
  # Apache Pulsar en modo standalone
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    profiles: ["pulsar"]
    hostname: broker
    restart: on-failure
    networks:
      - pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx1g
    command: bin/pulsar standalone
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1.5G"

  # Servicios de Salud Tech
  salud_tech:
    build:
      context: .
      dockerfile: src/salud_tech/Dockerfile
    container_name: salud_tech
    hostname: salud_tech
    profiles: ["salud_tech"]
    networks:
      - pulsar
      - db_network
    depends_on:
      salud_tech_db:
        condition: service_healthy
      
    environment:
      - FLASK_APP=src.salud_tech.api
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - HOST_ADDRESS=salud_tech
      - PULSAR_ADDRESS=broker
      - BROKER_HOST=broker
    ports:
      - "5000:5000"

  salud_tech_db:
    image: postgres:16-alpine
    profiles: ["salud_tech"]
    container_name: procesamiento_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salud_tech_123
      POSTGRES_DB: rabbit_salud_tech
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - db_network

  # Servicios de anonimacion
  anonimacion:
    build:
      context: .
      dockerfile: src/anonimacion/Dockerfile
    container_name: anonimacion
    hostname: anonimacion
    profiles: ["anonimacion"]
    networks:
      - pulsar
      - db_2_network
    environment:
      - FLASK_APP=src.anonimacion.api
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - HOST_ADDRESS=anonimacion
      - PULSAR_ADDRESS=broker
      - BROKER_HOST=broker
    ports:
      - "5001:5000"
    depends_on:
      anonimacion_db:
        condition: service_healthy

  anonimacion_db:
    image: postgres:16-alpine
    profiles: ["anonimacion"]
    container_name: anonimacion_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anonimacion_123
      POSTGRES_DB: rabbit_anonimacion
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - db_2_network

  # Servicios de mapear
  mapear:
    build:
      context: .
      dockerfile: src/mapear/Dockerfile
    container_name: mapear
    hostname: mapear
    profiles: ["mapear"]
    networks:
      - pulsar
      - db_mapear_network
    environment:
      - FLASK_APP=src.mapear.api
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PULSAR_ADDRESS=broker
      - BROKER_HOST=broker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mapear_123
      - POSTGRES_DB=rabbit_mapear
      - POSTGRES_HOST=mapear_db
    depends_on:
      mapear_db:
        condition: service_healthy
    ports:
      - "5002:5000"
    volumes:
      - ./src/mapear:/app/src/mapear

  mapear_db:
    image: postgres:16-alpine
    profiles: ["mapear"]
    container_name: mapear_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mapear_123
      POSTGRES_DB: rabbit_mapear
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - db_mapear_network

  saga-coordinator:
    profiles: ["sagas"]
    build: 
      context: .
      dockerfile: src/sagas/Dockerfile 
    restart: always
    networks:
    - pulsar

  bff-web:
    profiles: ["bff"]
    environment:
      - MAPEAR_URL=mapear:5000
    build:
      context: src/bff_web
    restart: always
    networks:
      - db_mapear_network
    ports:
      - "5004:8000"

  bff-mobile:
    profiles: ["bff"]
    environment:
      - MAPEAR_URL=mapear:5000
    build:
      context: src/bff_mobile
    restart: always
    networks:
      - db_mapear_network
    ports:
      - "5005:8000"